version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - QUEUE_MODE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - evolution_net
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - evolution_net

  postgres:
    image: postgres:13
    container_name:   
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution_net

  evolution-api:
    image: atendai/evolution-api
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=Teste123
      - API_PORT=8080
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    networks:
      - evolution_net

volumes:
  postgres_data:
  evolution_store:
  evolution_instances:

networks:
  evolution_net:
    driver: bridge
